CREATE TABLE [dbo].[ErrorRows] (
    [YearFFC]              NVARCHAR (50)  NULL,
    [MonthFFC]             NVARCHAR (50)  NULL,
    [DayofMonthFFC]        NVARCHAR (50)  NULL,
    [DayOfWeekFFC]         NVARCHAR (50)  NULL,
    [DepTimeFFC]           NVARCHAR (50)  NULL,
    [CRSDepTimeFFC]        NVARCHAR (50)  NULL,
    [ArrTimeFFC]           NVARCHAR (50)  NULL,
    [CRSArrTimeFFC]        NVARCHAR (50)  NULL,
    [UniqueCarrierFFC]     NVARCHAR (50)  NULL,
    [FlightNumFFC]         NVARCHAR (50)  NULL,
    [TailNumFFC]           NVARCHAR (50)  NULL,
    [ActualElapsedTimeFFC] NVARCHAR (50)  NULL,
    [CRSElapsedTimeFFC]    NVARCHAR (50)  NULL,
    [AirTimeFFC]           NVARCHAR (50)  NULL,
    [ArrDelayFFC]          NVARCHAR (50)  NULL,
    [DepDelayFFC]          NVARCHAR (50)  NULL,
    [OriginFFC]            NVARCHAR (50)  NULL,
    [DestFFC]              NVARCHAR (50)  NULL,
    [DistanceFFC]          NVARCHAR (50)  NULL,
    [TaxiInFFC]            NVARCHAR (50)  NULL,
    [TaxiOutFFC]           NVARCHAR (50)  NULL,
    [CancelledFFC]         NVARCHAR (50)  NULL,
    [CancellationCodeFFC]  NVARCHAR (50)  NULL,
    [DivertedFFC]          NVARCHAR (50)  NULL,
    [CarrierDelayFFC]      NVARCHAR (50)  NULL,
    [WeatherDelayFFC]      NVARCHAR (50)  NULL,
    [NASDelayFFC]          NVARCHAR (50)  NULL,
    [SecurityDelayFFC]     NVARCHAR (50)  NULL,
    [LateAircraftDelayFFC] NVARCHAR (50)  NULL,
    [RowNumber]            INT            NULL,
    [ErrorCode]            INT            NULL,
    [ErrorColumn]          INT            NULL,
    [ErrorColumnName]      NVARCHAR (500) NULL
);

